export const ERROR_CODES = {
  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_INVALID: 'MFA_INVALID',
  PASSWORD_REUSE: 'PASSWORD_REUSE',
  PASSWORD_TOO_WEAK: 'PASSWORD_TOO_WEAK',
  INVITE_EXPIRED: 'INVITE_EXPIRED',

  // Generic
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // Tenant
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_INACTIVE: 'TENANT_INACTIVE',

  // Business
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  SELF_APPROVAL: 'SELF_APPROVAL',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
};
